[[plugins]] # Haml
repo  = 'tpope/vim-haml'
on_ft = 'haml'

[[plugins]] # Html5
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'

[[plugins]] # deoplete
repo  = 'Shougo/deoplete.nvim'

[[plugins]] # deoplete
repo  = 'roxma/nvim-yarp'

[[plugins]] # deoplete
repo  = 'roxma/vim-hug-neovim-rpc'
